% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/toBiblatex.R, R/toBibtex.R
\name{toBiblatex}
\alias{toBiblatex}
\alias{toBibtex.BibEntry}
\alias{toBibtex}
\alias{toBibtex.BibEntry}
\title{Convert BibEntry objects to BibTeX or BibLaTeX}
\usage{
toBiblatex(object, ...)

\method{toBibtex}{BibEntry}(object, note.replace.field = c("urldate",
  "pubsate", "addendum"), extra.fields = NULL, ...)
}
\arguments{
\item{object}{an object of class BibEntry to be converted}

\item{...}{ignored}

\item{note.replace.field}{a character vector of BibLaTeX fields.  When converting an entry to BibTeX, the first field in the
entry that matches one specified in this vector will be added to the note field, \emph{if} the note field is not already
present}

\item{extra.fields}{character vector; fields that are not supported in standard BibTeX styles are by default dropped
in the result return by the toBibtex function.
Any fields specified in extra.fields will \emph{not} be dropped if present in an entry.}
}
\value{
an object of class \dQuote{Bibtex} - character vectors where each element holds one line of a BibTeX or BibLaTeX file
}
\description{
toBiblatex converts a BibEntry object to character vectors with BibLaTeX markup.  toBibtex will convert a BibEntry object
to charact